logging:
  level: DEBUG

spring:
  datasource:
    initialize: true
    schema: classpath:test/schema.sql
    data: classpath:test/data.sql
    sql-script-encoding: UTF-8
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

liquibase:
  enabled: false